[project]
name = "cciu"
version = "0.1.0"
description = "Computational clinical imaging utilities from the Computational Clinical Imaging Group"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.6",
    "pydicom>=3.0.2",
    "pydicom-seg",
    "pytest>=9.0.3",
    "requests>=2.33.1",
    "simpleitk>=2.5.4",
]

[build-system]
requires = ["uv_build>=0.11.13,<0.12"]
build-backend = "uv_build"

[tool.uv.sources]
pydicom-seg = { git = "https://github.com/josegcpa/pydicom-seg" }

[project.scripts]
cciu = "cciu.__main__:main_cli"
