[project]
name = "cciu"
version = "0.1.0"
description = "Computational clinical imaging utilities from the Computational Clinical Imaging Group"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.33.1",
    "simpleitk>=2.5.4",
]

[build-system]
requires = ["uv_build>=0.11.13,<0.12"]
build-backend = "uv_build"